init:
    $ end_text_rfe = "IIchan Eroge Team\nи Lilly On The Bible\nблагодарят вас за время, уделённое игре и моду!\n\nБлагодарности:\n\nPyTom'у за движок Ren'Py.\n\nСергею «SilentOwl» Ейбогу\nза предоставленный саундтрек.\n\nГруппе «Nobody.One» за\nпредоставленый саундтрек к моду.\n\nЛене\n за огроменную помощь с кодом мода и вычиткой\n\nАлексею «Mio Akiyama»\nза помощь с кодом мода.\n\nCпасибо Семёну «Мику» за помощь с Двачевской и поиском фонов.\n\nСпасибо Александру «PRO100_Sasha» за помощь с вычиткой.\n\n7дл-куну\n за разрешение на коммуниздинг спрайтов Мику\n\nМарсу Фохроеру\nза цг Юли.\n\nСайту freesounds.org\nза бесплатные звуки.\n\nСайтам iichan.hk и 2ch.hk.\n\nВсем, кто помогал работать над модом (ilyamodder, H8R и другие)\n\nВсем, кто поддерживал нас, ждал и верил!\n\nАвторы мода:\n\nBivnjatkO - сценарий.\n\ntlsd (Lilly On The Bible) - код, фоны, звуки, вычитка, отсебятина.\n\nЛена - внёс огромный вклад в развитие и выход мода вовремя.\n\n\nЭТО НЕ КОНЕЦ.\n"

init 2:
    $ pav = Character(u'Павел', color="#FF0066", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ mav = Character(u'Мать', color="#99CCFF", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ bab = Character(u'Зоя Фёдоровна', color="#3366CC", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ lis = Character(u'Лысый', color="#FFFF66", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ yar = Character(u'Ярик', color="#FF0033", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ bat = Character(u'Игнат Борисович', color="#06DCFB", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ pim = Character(u'Пионер Маньяк', color="#FF2626", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ prap = Character(u'Прапор', color="#40FF00", what_color="E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ aki = Character(u'Акира', color = "#0033FF", what_color = "#E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ fil = Character(u'Филин', color = "#8A2BE2", what_color = "#E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ ydm = Character(u'Девушка в красном', color = "#DC381F", what_color = "#E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    $ arsen = Character(u'Сеня', color = "#15BD77", what_color = "#E2C778", drop_shadow = [ (2, 2) ], drop_shadow_color = "#000", what_drop_shadow = [ (2, 2) ], what_drop_shadow_color = "#000")
    #Все бг / цг фил фри ту юз с указанием хотя бы ссылочки на мод. Всё обрабатывал сам и заняло это достаточно времени. Только, прошу, делайте неконфликтные моды, добавляйте в конец xxx_навзаниемода, так будет проще и мне, и вам.
    image bg gym = "bg/gym.jpg"
    image bg gym2 = "bg/gym2.jpg"
    image bg gym3 = "bg/gym3.jpg"
    image bg kitchenrfe = "bg/kitchen.jpg"
    image bg parad = "bg/paradnaya.jpg"
    image bg alisahru = "bg/int_alisa_hru.jpg"
    image bg babkaroom = "bg/babkaroom.jpg"
    image bg baseya = "bg/basementya.jpg"
    image bg batkokitchen = "bg/batkokitchen.jpg"
    image bg batkohouse = "bg/batkohouse.jpg"
    image bg kepepe = "bg/kepepe.jpg"
    image bg kladbiwe = "bg/kladbiwe.jpg"
    image bg sigroad = "bg/higroad.jpg"
    image bg bus_rfe = "bg/bus.jpg"
    image bg kremlin_rfe = "bg/kremlin.jpg"
    image bg nightroof_rfe = "bg/nightjaproof.jpg"
    image bg club1_rfe = "bg/club1.jpg"
    image bg club2_rfe = "bg/club2.jpg"
    image bg club4_rfe = "bg/club4.jpg"
    image bg svech_rfe = "bg/svech_rfe.jpg"
    image bg toiletc_rfe = "bg/toiletc.jpg"
    image cg onthescene_rfe_off = "bg/sceneoff.jpg"
    image cg onthescene_rfe_on = "bg/sceneon.jpg"
    image notdead_rfe = "bg/notdead.png"
    image bg mikuscreen_rfe = "bg/club3.jpg"
    image bg clubstreet_rfe = "bg/street.jpg"
    image bg hotelroom1_rfe = "bg/hotelroom1.jpg"
    image bg hotelroom2_rfe = "bg/hotelroom2.jpg"
    # И спрайты можете забирать с тем же условием. Создавайте новые имена! Не надо использовать coat/coattie. Такая схема подключения работает на 1.2.
    image dv smile coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_4_body.png",(0,0), "sprites/dv_4_coattie.png",(0,0), "images/sprites/normal/dv/dv_4_smile.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv normal coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_4_body.png",(0,0), "sprites/dv_4_coattie.png",(0,0), "images/sprites/normal/dv/dv_4_normal.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv surprise coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_1_body.png",(0,0), "sprites/dv_1_coattie.png",(0,0), "images/sprites/normal/dv/dv_1_surprise.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv scared coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_1_body.png",(0,0), "sprites/dv_1_coattie.png",(0,0), "images/sprites/normal/dv/dv_1_scared.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv shy coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_3_body.png",(0,0), "sprites/dv_3_coattie.png",(0,0), "images/sprites/normal/dv/dv_3_shy.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv sad coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_3_body.png",(0,0), "sprites/dv_3_coattie.png",(0,0), "images/sprites/normal/dv/dv_3_sad.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv guilty coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_3_body.png",(0,0), "sprites/dv_3_coattie.png",(0,0), "images/sprites/normal/dv/dv_3_guilty.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv angry coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_5_body.png",(0,0), "sprites/dv_5_coattie.png",(0,0), "images/sprites/normal/dv/dv_5_angry.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv cry coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_1_body.png",(0,0), "sprites/dv_1_coattie.png",(0,0), "images/sprites/normal/dv/dv_1_cry.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv laugh coattie = im.MatrixColor( im.Composite((900,1080), (0,0), "images/sprites/normal/dv/dv_4_body.png",(0,0), "sprites/dv_4_coattie.png",(0,0), "images/sprites/normal/dv/dv_4_laugh.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv laugh coattie close = im.MatrixColor( im.Composite((1050,1080), (0,0), "images/sprites/close/dv/dv_4_body.png",(0,0), "sprites/dv_4_coattie_close.png",(0,0), "images/sprites/close/dv/dv_4_laugh.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv smile coattie close = im.MatrixColor( im.Composite((1050,1080), (0,0), "images/sprites/close/dv/dv_4_body.png",(0,0), "sprites/dv_4_coattie_close.png",(0,0), "images/sprites/close/dv/dv_4_smile.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    image dv surprise coattie close = im.MatrixColor( im.Composite((1050,1080), (0,0), "images/sprites/close/dv/dv_1_body.png",(0,0), "sprites/dv_1_coattie_close.png",(0,0), "images/sprites/close/dv/dv_1_surprise.png"), im.matrix.tint(0.83, 0.88, 0.92) )
    #Semen/Pioneer - не помню, откуда взял. Честное слово. Дело было летом, откуда-то взял.
    image pi normal_rfe coat = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_coat.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_coat.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_coat.png"))
    image pi normal_rfe coat far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_coat.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_coat.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_coat.png"))
    image pi normal_rfe coat close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_coat.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_coat.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_coat.png"))

    image pi normal_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"))
    image pi normal_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_normal.png"))
    image pi normal_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_normal.png"))

    image pi normal_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"))
    image pi normal_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_normal.png"))
    image pi normal_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_normal.png"))

    image pi normal_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_normal.png"))
    image pi normal_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_normal.png"))
    image pi normal_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_normal.png"))

    image pi angry_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"))
    image pi angry_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_angry.png"))
    image pi angry_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_angry.png"))

    image pi angry_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_angry.png"))
    image pi angry_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_angry.png"))
    image pi angry_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_angry.png"))

    image pi grin_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"))
    image pi grin_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_grin.png"))
    image pi grin_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_grin.png"))

    image pi grin_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"))
    image pi grin_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_grin.png"))
    image pi grin_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_grin.png"))

    image pi grin_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_grin.png"))
    image pi grin_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_grin.png"))
    image pi grin_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_grin.png"))

    image pi serious_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"))
    image pi serious_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_serious.png"))
    image pi serious_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_serious.png"))

    image pi serious_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"))
    image pi serious_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_serious.png"))
    image pi serious_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_serious.png"))

    image pi serious_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_serious.png"))
    image pi serious_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_serious.png"))
    image pi serious_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_serious.png"))

    image pi shocked_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"))
    image pi shocked_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"))
    image pi shocked_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"))

    image pi shocked_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"))
    image pi shocked_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"))
    image pi shocked_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"))

    image pi shocked_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_shocked.png"))
    image pi shocked_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_shocked.png"))
    image pi shocked_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_shocked.png"))
    
    image pi smile_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"))
    image pi smile_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_smile.png"))
    image pi smile_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_smile.png"))

    image pi smile_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"))
    image pi smile_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_smile.png"))
    image pi smile_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_smile.png"))

    image pi smile_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_smile.png"))
    image pi smile_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_smile.png"))
    image pi smile_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_smile.png"))
    
    image pi surprise_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"))
    image pi surprise_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"))
    image pi surprise_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"))

    image pi surprise_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"))
    image pi surprise_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"))
    image pi surprise_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"))

    image pi surprise_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_surprise.png"))
    image pi surprise_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_surprise.png"))
    image pi surprise_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_surprise.png"))
    
    image pi upset_rfe swim = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_swim.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"))
    image pi upset_rfe swim far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_swim.png", (0, 0), "sprites/far/pi/pi_2_upset.png"))
    image pi upset_rfe swim close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_swim.png", (0, 0), "sprites/close/pi/pi_2_upset.png"))

    image pi upset_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_pioneer.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"))
    image pi upset_rfe far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_pioneer.png", (0, 0), "sprites/far/pi/pi_2_upset.png"))
    image pi upset_rfe close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_pioneer.png", (0, 0), "sprites/close/pi/pi_2_upset.png"))

    image pi upset_rfe shirt = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/normal/pi/pi_2_shirt.png", (0, 0), "sprites/normal/pi/pi_2_upset.png"))
    image pi upset_rfe shirt far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/far/pi/pi_2_shirt.png", (0, 0), "sprites/far/pi/pi_2_upset.png"))
    image pi upset_rfe shirt close = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080), (0, 0), "sprites/close/pi/pi_2_shirt.png", (0, 0), "sprites/close/pi/pi_2_upset.png"))
    
    #aki
    # сознательный говнокод говнокодом не считается #Можете забирать, спрайт взят с какой-то публичной ветки хентай-модификации. Нарыт лично сценаристом, так что несовпадение с вашим внутренним образом в голове валите на него. (я его представлял вообще другим)
    image aki normal = im.Composite((900,1080), (0,0), "sprites/aki/normal.png")
    image aki laugh = im.Composite((900,1080), (0,0), "sprites/aki/laugh.png")
    image aki grin = im.Composite((900,1080), (0,0), "sprites/aki/grin.png")
    image aki angry = im.Composite((900,1080), (0,0), "sprites/aki/angry.png")
    image aki afraid = im.Composite((900,1080), (0,0), "sprites/aki/afraid.png")
    #Мику-вокалоид. Взято с разрешения 7дл-куна.
    # And we have a winner. Сколько я мучился с Regex, это просто ужс. Зато удалил всякие схемы подключения get_sprite_ori или как-то так.
    # Если будете коммуниздить - прошу, ЗАМЕНИТЕ, внимание, ЗАМЕНИТЕ вот эти scene_rfe на что-нибудь другое (не на voca). И лучше спросите 7дл-куна.
    image mi cry scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_cry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_cry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_cry.png"))
    image mi dontlike scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_dontlike.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_dontlike.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_dontlike.png"))
    
    image mi laugh scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_laugh.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_laugh.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_laugh.png"))
    
    image mi scared scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_scared.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_scared.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_scared.png"))
    
    image mi shocked scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shocked.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shocked.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shocked.png"))
    
    image mi shy scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shy.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shy.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_shy.png"))
    
    image mi surprise scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_surprise.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_surprise.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_1_body.png", (0, 0), "sprites/mi/mi_1_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_1_surprise.png"))
    image mi cry_smile scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_cry_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_cry_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_cry_smile.png"))
    
    image mi grin scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_grin.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_grin.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_grin.png"))
    
    image mi happy scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_happy.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_happy.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_happy.png"))
    
    image mi sad scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_sad.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_sad.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_sad.png"))
    
    image mi smile scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_smile.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_smile.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_2_body.png", (0, 0), "sprites/normal/mi/mi_2_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_2_smile.png"))
    image mi angry scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_angry.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_angry.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_angry.png"))
    
    image mi normal scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_normal.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_normal.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_normal.png"))
    
    image mi rage scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_rage.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_rage.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_rage.png"))
    
    image mi serious scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_serious.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_serious.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_serious.png"))
    
    image mi upset scene_rfe = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_upset.png"), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_upset.png"), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), "images/sprites/normal/mi/mi_3_body.png", (0, 0), "sprites/normal/mi/mi_3_voca_dress.png", (0, 0), "images/sprites/normal/mi/mi_3_upset.png"))